USE SQLPRACTICE;
CREATE TABLE BRANCH(BRANCH_ID INT ,BRANCH_NAME VARCHAR(25));
INSERT INTO BRANCH (BRANCH_ID,BRANCH_NAME) VALUES (1,'VELACHERY');
INSERT INTO BRANCH (BRANCH_ID,BRANCH_NAME) VALUES (2,'OMR');
SELECT * FROM BRANCH;
CREATE TABLE STUDENTS(STU_ID INT,STU_NAME VARCHAR(25),DOJ TIMESTAMP,STU_COURSE_ID INT,BRANCH_ID INT);
INSERT INTO STUDENTS(STU_ID,STU_NAME,DOJ,STU_COURSE_ID,BRANCH_ID) VALUES (100,'SURYA',NOW(),1,1);
INSERT INTO STUDENTS(STU_ID,STU_NAME,DOJ,STU_COURSE_ID,BRANCH_ID) VALUES (101,'HARI',NOW(),2,1);
INSERT INTO STUDENTS(STU_ID,STU_NAME,DOJ,STU_COURSE_ID,BRANCH_ID) VALUES (102,'RAGHUL',NOW(),3,2);
SELECT * FROM STUDENTS;
CREATE TABLE COURSE(COURSE_ID INT,COURSE_NAME VARCHAR(25));
INSERT INTO COURSE(COURSE_ID,COURSE_NAME) VALUES (1,'FRONTEND');
INSERT INTO COURSE(COURSE_ID,COURSE_NAME) VALUES (2,'BACKEND');
INSERT INTO COURSE(COURSE_ID,COURSE_NAME) VALUES (3,'DATA ANALYST');
SELECT * FROM COURSE;
CREATE TABLE PAYMENT(STU_ID INT,PAYMENT INT,PAYMENT_PENDING INT);
INSERT INTO PAYMENT(STU_ID,PAYMENT,PAYMENT_PENDING) VALUES (100,10000,10000);
INSERT INTO PAYMENT(STU_ID,PAYMENT,PAYMENT_PENDING) VALUES (101,20000,15000);
INSERT INTO PAYMENT(STU_ID,PAYMENT,PAYMENT_PENDING) VALUES (102,30000,15000);
SELECT * FROM PAYMENT;
CREATE TABLE PLACEMENT(STU_ID INT,PLACED_COMPANY VARCHAR(25),CTC INT);
INSERT INTO PLACEMENT(STU_ID,PLACED_COMPANY,CTC) VALUES (100,'CTS',100000);
INSERT INTO PLACEMENT(STU_ID,PLACED_COMPANY,CTC) VALUES (101,'HCL',200000);
INSERT INTO PLACEMENT(STU_ID,PLACED_COMPANY,CTC) VALUES (102,'INFOSYS',300000);
SELECT * FROM PLACEMENT;
DROP TABLE PLACEMENT;
SELECT A.STU_NAME,B.BRANCH_NAME,C.COURSE_NAME,SUM(D.PAYMENT + D.PAYMENT_PENDING) AS TOTAL_PAYMENT,E.PLACED_COMPANY,E.CTC
FROM STUDENTS AS A
JOIN BRANCH AS B ON A.BRANCH_ID = B.BRANCH_ID
JOIN COURSE AS C ON A.STU_COURSE_ID = C.COURSE_ID 
JOIN PAYMENT AS D ON A.STU_ID = D.STU_ID 
JOIN PLACEMENT AS E ON A.STU_ID = E.STU_ID
GROUP BY A.STU_NAME,B.BRANCH_NAME,C.COURSE_NAME,E.PLACED_COMPANY,E.CTC;

CREATE TABLE EXAMPLE(EMP_ID INT,EMP_FNAME VARCHAR(20),EMP_LNAME VARCHAR(20),DOJ TIMESTAMP,EMP_SALARY FLOAT );
INSERT INTO EXAMPLE (EMP_ID,EMP_FNAME,EMP_LNAME,DOJ,EMP_SALARY) VALUES (1,'SURYA' ,'PRAKASH',NOW(),23458.8);
INSERT INTO EXAMPLE (EMP_ID,EMP_FNAME,EMP_LNAME,DOJ,EMP_SALARY) VALUES (2,'RAJ','KUMAR',NOW(),32567.4);
SELECT MONTHNAME(DOJ) FROM EXAMPLE WHERE EMP_ID=1;
SELECT EXTRACT( YEAR FROM DOJ) FROM EXAMPLE WHERE EMP_ID=1;
SELECT EXTRACT( MONTH FROM DOJ) FROM EXAMPLE WHERE EMP_ID=1;
SELECT EXTRACT( DAY FROM DOJ) FROM EXAMPLE WHERE EMP_ID=1;
SELECT ROUND(EMP_SALARY) FROM EXAMPLE WHERE EMP_ID=1;
SELECT SUBSTRING(EMP_NAME,7) FROM EXAMPLE WHERE EMP_ID=1;
SELECT CONCAT(EMP_FNAME,EMP_LNAME) FROM EXAMPLE WHERE EMP_ID=1;
SELECT TRUNCATE(EMP_SALARY,0) FROM EXAMPLE WHERE EMP_ID=1;
SELECT * FROM EXAMPLE;


SELECT * FROM EXAMPLE WHERE EMP_ID > ANY (SELECT EMP_ID FROM EXAMPLE WHERE EMP_SALARY>20000);
SELECT EMP_ID,EMP_FNAME,MAX(EMP_SALARY) FROM EXAMPLE GROUP BY EMP_FNAME,EMP_ID HAVING MAX(EMP_salary) > 25000;
SELECT EMP_FNAME,MIN(EMP_SALARY) FROM EXAMPLE GROUP BY EMP_FNAME HAVING MIN(EMP_salary) < 25000;
SELECT AVG(EMP_SALARY) AS AVG_SALARY FROM EXAMPLE;

CREATE VIEW STU_CTS AS SELECT * FROM PLACEMENT WHERE PLACED_COMPANY='CTS';
CREATE VIEW STU_CTS_CHECK AS SELECT * FROM PLACEMENT WHERE PLACED_COMPANY='CTS' WITH CHECK OPTION;
INSERT INTO STU_CTS_CHECK(STU_ID,PLACED_COMPANY) VALUES (101,'HCL');-----ERROR;
SELECT *  FROM STU_CTS;
SELECT * FROM STU_CTS_CHECK;
DROP VIEW STU_CTS;
DROP VIEW STU_CTS_CHECK;
CREATE VIEW STU_CTS_LATEST AS SELECT A.STU_NAME,B.BRANCH_NAME,C.COURSE_NAME,SUM(D.PAYMENT + D.PAYMENT_PENDING) AS TOTAL_PAYMENT,E.PLACED_COMPANY,E.CTC
FROM STUDENTS AS A
JOIN BRANCH AS B ON A.BRANCH_ID = B.BRANCH_ID
JOIN COURSE AS C ON A.STU_COURSE_ID = C.COURSE_ID 
JOIN PAYMENT AS D ON A.STU_ID = D.STU_ID 
JOIN PLACEMENT AS E ON A.STU_ID = E.STU_ID
GROUP BY A.STU_NAME,B.BRANCH_NAME,C.COURSE_NAME,E.PLACED_COMPANY,E.CTC HAVING PLACED_COMPANY='CTS';
SELECT * FROM STU_CTS_LATEST;
 CREATE TABLE STUDENTTABLE LIKE STUDENTS;
 SELECT * FROM STUDENTTABLE;
 CREATE TABLE  
 